services:

# Redis server that act as a pubsub and 'WebSocket handler'.
  pubsub:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: chatapp
    networks:
      - chatnet

# Websocket Server: This service will listen on port 3000 and run 4 replicas.
  websocketserver:
    build: ./websocketserver
    environment:
      REDIS_URL: redis://:chatapp@pubsub:6379/0
    depends_on:
      - pubsub
    networks:
      - chatnet
    expose:
      - "3000"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure

# Load Balancer: This service acts as a load balancer for the websocketserver replicas.
# It listens on port 8080 and forwards requests to the websocketserver replicas.
  loadbalancer:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - websocketserver
    networks:
      - chatnet

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - loadbalancer
    networks:
      - chatnet

networks:
  chatnet:  
    driver: bridge
