services:
  pubsub:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: chatapp
    networks:
      - chatnet

  websocketserver:
    build: ./backend
    environment:
      REDIS_URL: redis://:chatapp@pubsub:6379/0
    depends_on:
      - pubsub
    networks:
      - chatnet
    expose:
      - "3000"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure

  loadbalancer:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - websocketserver
    networks:
      - chatnet

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - loadbalancer
    networks:
      - chatnet

networks:
  chatnet:  
    driver: bridge
