services:
  pubsub:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: chatapp
    networks:
      - chatnet

  backend:
    build: ./backend
    environment:
      REDIS_URL: redis://:chatapp@pubsub:6379/0
    depends_on:
      - pubsub
    networks:
      - chatnet
    expose:
      - "3000"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - chatnet

networks:
  chatnet:  
    driver: bridge
